config/routes.rb
Rails.application.routes.draw do
  

  devise_for :users
  get "search_user", to: "users#search_user"

  
  resources :items
  delete 'destroy_item', to: 'items#destroy', as: 'destroy_item'
  get "admin_search", to: "items#admin_search"

  resources :orders
  root 'pages#dashboard'
  get "welcome", to: "pages#welcome"
  get 'admin', to: "pages#admin"
  post 'add_order', to: 'orders#create'
  delete "remove_order", to: "orders#destroy"
  post "add_like", to: "likes#create"
  delete "remove_like", to: "likes#destroy"
  get "favorites", to: "likes#index"
  get "search_item", to: "items#search"
  get "all_items", to: 'pages#all_items'
  get "all_users", to: 'pages#all_users'
  post "make_admin", to: "pages#make_admin"
  delete "delete_user", to: "pages#delete_user"
  post "undo_admin", to: "pages#undo_admin"
  get "all_orders", to: "pages#all_orders"

  get '*a' => "items#index",
  :constraints => { :not_found => /.*/ }
end

app/views/search/_search-component.html.erb
<%= form_tag search_item_path, remote: true, method: :get do %>
    <div class="form group row">
        <div class="col-sm-9 no-right-padding">
            <%= text_field_tag :item, params[:item], placeholder: 'Search..', autofocus: true, class: 'form-control form-control-lg' %>
        </div>
        <div class="col-sm-3 no-left-padding">
            <%= button_tag type: :submit, class: 'btn btn-success' do %>
                <%= fa_icon 'search 2x' %>
            <% end %>
        
        </div>
    </div>
<% end %>