config/routes.rb
Rails.application.routes.draw do
  

  devise_for :users
  get "search_user", to: "users#search_user"

  
  resources :items
  delete 'destroy_item', to: 'items#destroy', as: 'destroy_item'
  get "admin_search", to: "items#admin_search"

  resources :orders
  root 'pages#dashboard'
  get "welcome", to: "pages#welcome"
  get 'admin', to: "pages#admin"
  post 'add_order', to: 'orders#create'
  delete "remove_order", to: "orders#destroy"
  post "add_like", to: "likes#create"
  delete "remove_like", to: "likes#destroy"
  get "favorites", to: "likes#index"
  get "search_item", to: "items#search"
  get "all_items", to: 'pages#all_items'
  get "all_users", to: 'pages#all_users'
  post "make_admin", to: "pages#make_admin"
  delete "delete_user", to: "pages#delete_user"
  post "undo_admin", to: "pages#undo_admin"
  get "all_orders", to: "pages#all_orders"

  get '*a' => "items#index",
  :constraints => { :not_found => /.*/ }
end

app/views/pages/admin.html.erb
<h1>Welcome Admin</h1>




<div class="card">
  <div class="card-header">
    <i class="fa fa-eye 2x"></i>
  </div>
  <div class="card-body">
    <h5 class="card-title">View All Items Present In Systems</h5>
    <p class="card-text">Admin can View all the items present in database and perform some actions</p>
    <%= link_to "View All Items", all_items_path, class: "btn btn-primary" %>

   </div>
</div>


<div class="card">
  <div class="card-header">
    <i class="fa fa-street-view 2x"></i>
  </div>
  <div class="card-body">
    <h5 class="card-title">View All Users Present In Systems</h5>
    <p class="card-text">Admin can View all the users present in database and perform some actions</p>
    <%= link_to "View All Users", all_users_path,  class: "btn btn-primary" %>
  </div>
</div>




<div class="card">
  <div class="card-header">
  <i class="fa fa-plus-circle"></i>
  </div>
  <div class="card-body">
    <h5 class="card-title">Add A New Item To System</h5>
    <p class="card-text">Admin can add a new item in database and perform some actions</p>
    <%= link_to "Add New Item", new_item_path, class: "btn btn-primary" %>
  </div>
</div>

app/views/pages/all_items.html.erb
<% if @all_items.present? %>
  

<h3>Search Item</h3>
<%= form_tag admin_search_path, remote: true, method: :get do %>
  <div class="form group row">
      <div class="col-sm-9 no-right-padding">
          <%= text_field_tag :item, params[:item], placeholder: 'Search..', autofocus: true, class: 'form-control form-control-lg' %>
      </div>
      <div class="col-sm-3 no-left-padding">
          <%= button_tag type: :submit, class: 'btn btn-success' do %>
              <%= fa_icon 'search 2x' %>
          <% end %>
      
      </div>
  </div>
<% end %>


<div id="itemsResult">


  <table class="table table-striped">
      <thead>
        <tr>
          <th scope="col">Image</th>
          <th scope="col">Item Name</th>
          <th scope="col">Price</th>
          <th scope="col">Added by</th>
          <th scope="col">Actions</th>
        </tr>
      </thead>
      <% @all_items.each do |item| %>
      <tbody>
      <tr>
        <th scope="row">
          <%= link_to item do %>
            <%= image_tag item.picture.url, size: '100x80' %>
          <% end %>
        </th>
            <td><%= item.name %></td>
            <td><%= item.price %></td>
            <td><%= get_added_by(item.id) %></td>
            <td>
                <%= link_to "Edit", edit_item_path(item.id), class: "btn btn-primary" %>
                <%= link_to "Delete", destroy_item_path(id: item.id) , class: "btn btn-danger", method: :delete, data: {confirm: "Are you sure?"}%>
            </td>
            
        </tr>
        
      </tbody>
    <% end %>
    </table>  
</div>

<% else %>
    <h5>No Item Added Yet!</h5>
    <%= link_to "Add New Item", new_item_path, class: "btn btn-primary" %>
<% end %>

app/views/pages/all_orders.html.erb
<% if @orders.empty? %>
  <h1>No Order Yet!</h1>
<% else %>

  <h1>Orders Listing</h1>

  <table class="table table-striped">
    <thead>
      <tr>
        <th scope="col"></th>
        <th scope="col">Item Name</th>
        <th scope="col">Price</th>
        <th scope="col">Quantity</th>
        <th scope="col">Ordered By</th>
        <th scope="col">Net Bill</th>
        <th scope="col">Date</th>
      </tr>
    </thead>
    <% @orders.each do |order| %>
    <tbody>
      <tr>
        <th scope="row">
          <%= link_to get_item(order.item_id) do %>
            <%= image_tag get_item_picture(order.item_id), size: '100x80' %></th>
          <% end %>
        <td><%= get_item_name(order.item_id)%></td>
        <td>$ <%= get_item_price(order.item_id)%></td>
        <td>1</td>
        <td><%= get_user_name(order.id)%></td>
        <td>$ <%= get_item_price(order.item_id)%></td>
        <td><%= order.created_at.to_date.strftime('%a, %e %b %y') %></td>
      </tr>
      
    </tbody>
    <% end %>
  </table>
<% end %>

app/views/pages/all_users.html.erb
<% if @all_users.present? %>
    <div class="container">
        <h1>All Users</h1>

        <%= form_tag search_user_path, remote: true, method: :get do %>
            <div class="form group row">
                <div class="col-sm-9 no-right-padding">
                    <%= text_field_tag :user, params[:user], placeholder: 'Search..', autofocus: true, class: 'form-control form-control-lg' %>
                </div>
                <div class="col-sm-3 no-left-padding">
                    <%= button_tag type: :submit, class: 'btn btn-success' do %>
                        <%= fa_icon 'search 2x' %>
                    <% end %>
                
                </div>
            </div>
        <% end %>

        <div id="usersResult">
        

        <table class="table table-striped">
        <thead>
            <tr>
                <th scope="col">User ID</th>
                <th scope="col">Full Name</th>
                <th scope="col">Orders</th>
                <th scope="col">Likes</th>
                <th scope="col">Actions</th>
            </tr>
        </thead>
        <% @all_users.each do |user| %>
            <tbody>
            <tr>
                    <th scope="row"><%= user.id%></th>
                    <td><%= get_user_full_name(user.id) %></td>
                    <td><%= get_user_orders(user.id) %></td>
                    <td><%= get_user_likes(user.id) %></td>
                    <td>
                        <%= link_to "Make ADMIN", make_admin_path(id: user.id), remote: true, class: "btn btn-primary", method: :post%>
                    </td>
            </tr>
                
            </tbody>
        <% end %>
        </table>
    </div>
<% end %>
<% if @admins.present? %>
    <h1>Admins</h1>
    
    <table class="table table-striped">
    <thead>
        <tr>
        <th scope="col">User ID</th>
        <th scope="col">Full Name</th>
        <th scope="col">Orders</th>
        <th scope="col">Likes</th>
        <th scope="col">Actions</th>
        </tr>
    </thead>
    <% @admins.each do |admin| %>
    <tbody>
    <tr>
            <th scope="row"><%= admin.id%></th>
            <td><%= get_user_full_name(admin.id) %></td>
            <td><%= get_user_orders(admin.id) %></td>
            <td><%= get_user_likes(admin.id) %></td>
            <td>
                <% if current_user != admin %>
                    <%= link_to "Make User", undo_admin_path(id: admin.id), remote: true, class: "btn btn-danger", method: :post %>
                <% end %>
            </td>
            
        </tr>
        
    </tbody>
    <% end %>
    </table>

</div>
<% end %>

app/views/pages/welcome.html.erb
<h1>Welcome :) </h1>