config/routes.rb
Rails.application.routes.draw do
  

  devise_for :users
  get "search_user", to: "users#search_user"

  
  resources :items
  delete 'destroy_item', to: 'items#destroy', as: 'destroy_item'
  get "admin_search", to: "items#admin_search"

  resources :orders
  root 'pages#dashboard'
  get "welcome", to: "pages#welcome"
  get 'admin', to: "pages#admin"
  post 'add_order', to: 'orders#create'
  delete "remove_order", to: "orders#destroy"
  post "add_like", to: "likes#create"
  delete "remove_like", to: "likes#destroy"
  get "favorites", to: "likes#index"
  get "search_item", to: "items#search"
  get "all_items", to: 'pages#all_items'
  get "all_users", to: 'pages#all_users'
  post "make_admin", to: "pages#make_admin"
  delete "delete_user", to: "pages#delete_user"
  post "undo_admin", to: "pages#undo_admin"
  get "all_orders", to: "pages#all_orders"

  get '*a' => "items#index",
  :constraints => { :not_found => /.*/ }
end

app/models/item.rb
class Item < ApplicationRecord

  belongs_to :user
  has_many :orders, :dependent => :destroy
  has_many :users, through: :orders

  has_many :likes, :dependent => :destroy
  has_many :users, through: :likes

  mount_uploader :picture, PictureUploader
  validates :name,  presence: true, uniqueness: true
  validates :price, :picture, presence: true
  validate :picture_size
  validate :neg_price


    # //Search Helpers
  def self.search(param)
      param.strip!
      to_send_back = (id_matches(param) + name_matches(param) + price_matches(param)).uniq
      return nil unless to_send_back
      to_send_back
  end

  def self.id_matches(param)
    matches('id', param)
  end

  def self.name_matches(param)
    matches('name', param)
  end

  def self.price_matches(param)
    matches('price', param)
  end

  def self.matches(field_name, param)
    where("#{field_name} like ?", "%#{param}%" )
  end

  # //search helper ends

  
  private

  def picture_size
    if picture.size > 5.megabytes
      errors.add(:picture, "should be less than 5 MB")
    end
  end

  def neg_price
    if price < 1
      errors.add(:price, "can't be negative or zero")
    end
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
    
    rescue_from ActionView::MissingTemplate, :with => :not_found

    skip_before_action :authenticate_user!, only: [:index, :search]
    before_action :set_item, only: [:show, :destroy, :update, :require_same_user]
    before_action :require_admin, only: [:new, :create, :edit, :destroy, :update, :admin_search]
    before_action :require_same_user, only: [:edit, :destroy, :update]

    def index
        @items = Item.all
        # respond_to do |format|
        #   format.html
        #   format.json
        # end
    end

    def new
        @item = Item.new
    end 

    def edit
    
    end

    def show
      @item = Item.find(params[:id])
    end

    def create
        @item = Item.new(item_params)
        @item.user = current_user
        if @item.save
            flash[:notice] = "Item was created successfully"
            redirect_to items_path
        else
            flash[:alert] = 'Something went wrong white creating new item'
            render 'new'
        end
    end


    def update
      if @item.update(item_params)
        flash[:notice] = "Item updated successfully!"
        redirect_to @item
    else
        render 'edit'
    end

    
    end
    def destroy
      if @item.destroy 
        flash[:notice] = "Item deleted successfully!"
      else
        flash[:alert] = "Something went wrong!"
      end 
      redirect_back fallback_location: items_path

    end

    def search
      if params[:item].present?
        @item = Item.search(params[:item])
            if !@item.empty?
              respond_to do |format|
                format.js {render partial: 'items/items-result'} 
              end
            else
              respond_to do |format|
                flash.now[:alert] = "No item found"
                format.js {render partial: 'items/items-result'}
              end
              # flash[:notice] = 'Please enter a valid name'  
              # redirect_to request.referrer
            end

        else
          respond_to do |format|
            flash.now[:alert] = "Enter somthing to search"
            format.js {render partial: 'items/items-result'}
          end
        end
    end

    def admin_search
      if params[:item].present?
        @item = Item.search(params[:item])
            if !@item.empty?
              respond_to do |format|
                format.js {render partial: 'pages/search/items-result'} 
              end
            else
              respond_to do |format|
                flash.now[:alert] = "No item found"
                format.js {render partial: 'pages/search/items-result'} 
              end
              # flash[:notice] = 'Please enter a valid name'  
              # redirect_to request.referrer
            end

        else
          respond_to do |format|
            flash.now[:alert] = "Enter somthing to search"
            format.js {render partial: 'pages/search/items-result'} 
          end
        end
    end


      
  private
  # Use callbacks to share common setup or constraints between actions.
  def set_item
    @item = Item.find(params[:id]) rescue not_found
  end
  # Only allow a list of trusted parameters through.
  def item_params
    params.require(:item).permit(:name, :price, :picture)
  end


  def require_same_user
      @item = Item.find(params[:id]) rescue not_found
      if @item.present?
        if current_user.admin != true
          flash[:notice] = "This action is forbidden for you!"
          redirect_to root_path
        end
      else
        flash[:notice] = "Item not found!"
        redirect_to items_path
      end
  end

  def not_found
    flash[:alert] = "Something is missing!"
    redirect_to root_path
  end


end

app/views/items/_index.html.erb
<div class="containe">
    <h1 class="title">Items Listing</h1>

    <% if !@items.present? %>
            <h4 align="center">
                No item Available!
            </h4>
    <% else %>
    
    <div class="card-deck">
        <% @items.each do |item| %>
            <div class="row">
                <div class="col-12">
                    <div class="item">
                        <div class="card item">
                            
                            <%= link_to item do %>
                                <%= image_tag item.picture.url, size: '276x180', class: "card-img-top" %>
                            <% end %>
                            <div class="card-body">
                                <h5 class="card-title"><%= item.name %></h5>
                                <h8 class="card-title">$ <%= item.price %></h8>
                            </div>
                            <div class="card-footer" >
                                <small class="text-muted"><%= item.updated_at.to_date.strftime('%a, %e %b %y') %></small>
                                <% if signed_in? %>
                                    <% if already_liked?(item, current_user)%>
                                        <%= link_to 'Liked <i class="fa fa-thumbs-down "></i>'.html_safe, remove_like_path(id: item.id), :id => 'my-link', remote: true, class: "like dontscroll", method: :delete %></a>
                                    <% else %>
                                        <%= link_to 'Like <i class="fa fa-thumbs-up "></i>'.html_safe, add_like_path(id: item.id), :id => 'my-link', remote: true, class: "like", method: :post %></small>
                                    <% end %>
                                <% end %>    
                            </div>
                            <% if signed_in? %>
                                <% if current_user.already_included?(item, current_user) %>
                                    <%= link_to 'Remove from Cart', remove_order_path(id: item.id), class: 'btn btn-danger', remote: true, method: :delete %>
                                <% else %>
                                    <%= link_to 'Add To Cart', add_order_path(item_id: item.id), class: 'btn btn-primary', remote: true, method: :post %>
                                <% end %>
                            <% end %>
                        </div>
                    </div>
                </div>
            </div>
        <% end %>
    </div>
                
<% end %>
</div>
    


<script>
function scrollWin() {
  window.scrollTo();
}
</script>

app/views/items/_items-result.html.erb
<%= render 'layouts/messages/errors'%>              
<% if @item.present? %>

<div class="card-deck">
<% @item.each do |item| %>
      <div class="row">
          <div class="col-12">
              <div class="item">
                  <div class="card item">
                      
                      <%= link_to item do %>
                          <%= image_tag item.picture.url, size: '276x180', class: "card-img-top" %>
                      <% end %>
                      <div class="card-body">
                          <h5 class="card-title"><%= item.name %></h5>
                          <h8 class="card-title">$ <%= item.price %></h8>
                      </div>
                      <div class="card-footer" >
                          <small class="text-muted"><%= item.updated_at.to_date.strftime('%a, %e %b %y') %></small>
                          <% if signed_in? %>
                              <% if already_liked?(item, current_user)%>
                                  <%= link_to 'Liked <i class="fa fa-thumbs-down "></i>'.html_safe, remove_like_path(id: item.id), :id => 'my-link', remote: true, class: "like dontscroll", method: :delete %></a>
                              <% else %>
                                  <%= link_to 'Like <i class="fa fa-thumbs-up "></i>'.html_safe, add_like_path(id: item.id), :id => 'my-link', remote: true, class: "like", method: :post %></small>
                              <% end %>
                          <% end %>    
                      </div>
                      <% if signed_in? %>
                          <% if current_user.already_included?(item, current_user) %>
                              <%= link_to 'Remove from Cart', remove_order_path(id: item.id), class: 'btn btn-danger', remote: true, method: :delete %>
                          <% else %>
                              <%= link_to 'Add To Cart', add_order_path(item_id: item.id), class: 'btn btn-primary', remote: true, method: :post %>
                          <% end %>
                      <% end %>
                  </div>
              </div>
          </div>
      </div>
  <% end %>
  </div>
<% else %>


  <%= render 'items/index' %>
<%  end %>

app/views/items/_items-result.js.erb
document.querySelector('#items-result').innerHTML = '<%= j render 'items-result.html' %>'

app/views/items/edit.html.erb
<div class="conatainer">

<h1 align="center">Edit Item</h1>
<div class="row">
  <div class="col-9">
    <%= form_for @item, :html => { multiport: true, :class => "form-horizontal "} do |form| %>
      <% if @item.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

          <ul>
            <% @item.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="form-group">
        <%= form.label :name %>
        <%= form.text_field :name, autofocus: true, autocomplete: 'name', class: 'form-control' %>
      </div>


      <div class="form-group">
        <%= form.label :price %>
        <%= form.text_field :price, autofocus: true, autocomplete: 'price', class: 'form-control' %>
    </div>


      <div class="form-group">
        <%= form.label :picture %>
        <%= form.file_field :picture, accept: 'image/jpeg , image/gif, image/png', autofocus: true, class: 'form-control' %>
      </div>
      


      <div class="actions">
        <%= form.submit %>
      </div>
    <% end %>
  </div>
</div>
</div>


<script type="text/javascript">
  $('#item_picture').bind('change', function(){
    var size_in_megabytes = this.files[0].size/1024/1024;
    if(size_in_megabytes > 5){
      alert('Maximum file size is 5MB')
    }
  });

</script>

app/views/items/index.html.erb
<div id="items-result">
    <%= render "items/index" %>

</div>

app/views/items/new.html.erb
<h1 class="title">Add New Item</h1>
<div class="new-item-form">
    <div class="conatainer">
    <div class="row">
      <div class="col-9">
        <%= form_for @item, :html => { multiport: true, :class => "form-horizontal "} do |form| %>
          <% if @item.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

              <ul>
                <% @item.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
              </ul>
            </div>
          <% end %>

          <div class="form-group">
            <%= form.label :name %>
            <%= form.text_field :name, autofocus: true, autocomplete: 'name', class: 'form-control' %>
          </div>


          <div class="form-group">
            <%= form.label :price %>
            <%= form.text_field :price, autofocus: true, autocomplete: 'price', class: 'form-control' %>
        </div>


          <div class="form-group">
            <%= form.label :picture %>
            <%= form.file_field :picture, accept: 'image/jpeg , image/gif, image/png', autofocus: true, class: 'form-control' %>
          </div>
          


          <div class="actions">
            <%= form.submit %>
          </div>
        <% end %>
      </div>
    </div>
    </div>
</div>


<script type="text/javascript">
  $('#item_picture').bind('change', function(){
    var size_in_megabytes = this.files[0].size/1024/1024;
    if(size_in_megabytes > 5){
      alert('Maximum file size is 5MB')
    }
  });

</script>

app/views/items/show.html.erb
<h1 align="center">Item Derails</h1>

<div class="container">
    <div class="card-deck">
        <div class="row">
            <div class="col">
                <div class="card item">
                <%= image_tag @item.picture.url, size: "276x180", class: "card-img-top" %>
                <div class="card-body">
                    <h5 class="card-title"><%= @item.name %></h5>
                    <h8 class="card-title">$ <%= @item.price %></h8>
                    <br>
                    <h8 class="card-title"><%= get_likes_count(@item.id)%> people like this product! </h8>
                </div>
                <div class="card-footer">
                    <small class="text-muted"><%= @item.updated_at.to_date.strftime('%a, %e %b %y') %> 
                    <% if signed_in? %>
                        <% if already_liked?(@item, current_user)%>
                            <%= link_to '<i class="fa fa-thumbs-down "></i>'.html_safe, remove_like_path(id: @item.id), class: "like", method: :delete %></small>
                        <% else %>
                            <%= link_to '<i class="fa fa-thumbs-up "></i>'.html_safe, add_like_path(id: @item.id), class: "like", method: :post %></small>
                        <% end %>
                    <% end %>    
                </div>
                <% if signed_in? %>
                    <% if current_user.already_included?(@item, current_user) %>
                        <%= link_to 'Remove from Cart', remove_order_path(id: @item.id), class: 'btn btn-danger', method: :delete %>
                    <% else %>
                        <%= link_to 'Add To Cart', add_order_path(item_id: @item.id), class: 'btn btn-primary', method: :post %>
                    <% end %>
                <% end %>
            </div>
        </div>
    </div>
</div>