config/routes.rb
Rails.application.routes.draw do
  

  devise_for :users
  get "search_user", to: "users#search_user"

  
  resources :items
  delete 'destroy_item', to: 'items#destroy', as: 'destroy_item'
  get "admin_search", to: "items#admin_search"

  resources :orders
  root 'pages#dashboard'
  get "welcome", to: "pages#welcome"
  get 'admin', to: "pages#admin"
  post 'add_order', to: 'orders#create'
  delete "remove_order", to: "orders#destroy"
  post "add_like", to: "likes#create"
  delete "remove_like", to: "likes#destroy"
  get "favorites", to: "likes#index"
  get "search_item", to: "items#search"
  get "all_items", to: 'pages#all_items'
  get "all_users", to: 'pages#all_users'
  post "make_admin", to: "pages#make_admin"
  delete "delete_user", to: "pages#delete_user"
  post "undo_admin", to: "pages#undo_admin"
  get "all_orders", to: "pages#all_orders"

  get '*a' => "items#index",
  :constraints => { :not_found => /.*/ }
end

app/views/layouts/navigation/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
  

  
        <%= link_to "Shop", root_path, class: "navbar-brand" %>
            
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <% if signed_in? && (current_user.admin != true || request.path == items_path) %>
            <% if signed_in?  %>
                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav mr-auto">
                            <li class="nav-item <%= 'active' if request.path == items_path %>">
                                <%= link_to "Home", items_path, class:'nav-link'  %>
                            </li>
                            <li class="nav-item <%= 'active' if request.path == orders_path %>">
                                <%= link_to 'Orders', orders_path, class: "nav-link" %>
                            </li>
                            <li class="nav-item <%= 'active' if request.path == favorites_path %>">
                                <%= link_to 'Favorites', favorites_path, class: "nav-link" %>
                            </li>                        
                        </ul>
                        <%= render 'search/search-component' %>

                        

                        <ul class="navbar-nav ml-auto class="form-inline my-2 my-lg-0"">
                            
                                <!-- Cart Button -->
                            <div class="btn-group my_info my_cart_button">
                                <button type="button" class="btn btn btn-info top " data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <i class="fa fa-shopping-cart "> (<%= current_user.get_orders().count %> )</i>
                                </button>
                                <div class="dropdown-menu">
                                    <%= render "layouts/cart/cart" %>
                                </div>
                            </div>
                            <li class="nav-item dropdown my_info">
                                <a class="nav-link " href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    <% if current_user.profile_picture.url %>
                                        <%= image_tag current_user.profile_picture.url, size: '50x50', class: "profile-picture" %>
                                    <% else %>
                                        <%= fa_icon 'user 2x' %>
                                    <% end %>    
                                    <%= current_user.full_name if current_user %>
                                </a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <%= link_to 'Edit Profile', edit_user_registration_path, class: 'dropdown-item' %>
                                <div class="dropdown-divider"></div>
                                    <% if signed_in? %>
                                        <%= link_to "Logout", destroy_user_session_path, class: 'btn btn btn-danger logout-button dropdown-item', method: :delete %>
                                    <% end %>
                                
                                </div>
                        </li>
                        </ul>

                    </ul>
                    </div>
            <% else %>
                    <%= link_to "Login", new_user_session_path, class: 'btn btn btn-success logout-button' %>
            <% end %>

        <% else  %>
            <% if signed_in? %>
            <div class="collapse navbar-collapse " id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    
                    <li class="nav-item <%= 'active' if request.path == items_path %>">
                        <%= link_to "Home", admin_path, class:'nav-link'  %>
                    </li>
                    <li class="nav-item <%= 'active' if request.path == all_orders_path %>">
                        <%= link_to 'Orders', all_orders_path, class: "nav-link" %>
                    </li>


                    <li class="nav-item <%= 'active' if request.path == items_path %>">
                        <%= link_to "User View", items_path, class:'nav-link'  %>
                    </li>
                
                    <li class="nav-item dropdown my_info admin-profile">
                        <a class="nav-link " href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <% if current_user.profile_picture.url %>
                                <%= image_tag current_user.profile_picture.url, size: '50x50', class: "profile-picture" %>
                            <% else %>
                                <%= fa_icon 'user 2x' %>
                            <% end %>    
                            <%= current_user.full_name if current_user %>
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <%= link_to 'Edit Profile', edit_user_registration_path, class: 'dropdown-item' %>
                        <div class="dropdown-divider"></div>
                            <% if signed_in? %>
                                <%= link_to "Logout", destroy_user_session_path, class: 'btn btn btn-danger logout-button dropdown-item', method: :delete %>
                            <% end %>
                        
                        </div>
                    </li>
                </ul>
            </div>
            <% end %>
        <% end %>

    </div>
</nav>

app/views/layouts/navigation/_sidebar.html.erb
<!doctype html>
<html lang="en">
  <head>
  	<title>Sidebar 01</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700,800,900" rel="stylesheet">
		
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
		<link rel="stylesheet" href="css/style.css">
  </head>
  <body>
		
		<div class="wrapper d-flex align-items-stretch">
            <nav id="sidebar">
                <div class="p-4 pt-5">
                    <ul class="list-unstyled components mb-5">
                        <li> 
                        <a href="">Home</a>
                        </li>

                        <li> 
                        <a href="">Orders</a>
                        </li>

                        <li> 
                        <a href="">History</a>
                        </li>
                        
                    </ul>
                </div>
            </nav>
            <!-- Page Content  -->
            
            

    <script src="js/jquery.min.js"></script>
    <script src="js/popper.js"></script>
    <script src="js/bootstrap.min.js"></script>
    <script src="js/main.js"></script>
  </body>
</html>